package com.wilson.tasker.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wilson.tasker.dao.SceneActivity;

import com.wilson.tasker.dao.SceneActivityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sceneActivityDaoConfig;

    private final SceneActivityDao sceneActivityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sceneActivityDaoConfig = daoConfigMap.get(SceneActivityDao.class).clone();
        sceneActivityDaoConfig.initIdentityScope(type);

        sceneActivityDao = new SceneActivityDao(sceneActivityDaoConfig, this);

        registerDao(SceneActivity.class, sceneActivityDao);
    }
    
    public void clear() {
        sceneActivityDaoConfig.getIdentityScope().clear();
    }

    public SceneActivityDao getSceneActivityDao() {
        return sceneActivityDao;
    }

}
